### ISSUE TITLE
Added Pagination while searching users.

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-ldap#1]
> **Adding feature to search user with pagination?**
 - [ ] Why is the new feature needed? What purpose does it serve?

Most of Active directory has a limit of request users like 1k or 5k and if you need to get more users like 10k we need to use search and get users data with pagination.

-   [ ] How will users use the new feature?

```php
        $users = $this->zendLdap->multiPageSearch($filter, $baseDn, $scope, $fields);
        return $users;
```

---

Originally posted by @ArchTaqi at https://github.com/zendframework/zend-ldap/pull/81

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
