### ISSUE TITLE
Replace occurrences of DateTime-Typehint with DateTimeInterface where appropriate

### ISSUE THREAD

**Issue by weierophinney** [laminas/laminas-ldap#3]
I've noticed that there are some DateTime-Typehints that should be replaced with DateTimeInterface to allow passing of DateTimeImmutable as well.

---

Originally posted by @heiglandreas at https://github.com/zendframework/zend-ldap/issues/58

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
