### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by GuySartorelli** [laminas/laminas-ldap#46]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | no
| BC Break    | no

#### Summary

The PHP dependency constraint is very strict, and doesn't allow new versions of PHP to be used as they come out:
`"php": "~8.0.0 || ~8.1.0 || ~8.2.0",`

Please either loosen this constraint so that people can use newer versions of PHP as they come out (e.g. `^8.0.0`), or else add official support for PHP 8.3 now that it has been released.

**Comment by froschdesign** [comment]
@GuySartorelli 
> Please either loosen this constraint so that people can use newer versions of PHP as they come out (e.g. `^8.0.0`), or else

Unfortunately, PHP does not follow semantic versioning and brings backward compatibility breaks with every minor version:

- https://www.php.net/releases/8.3/en.php#deprecations_and_bc_breaks
- https://www.php.net/releases/8.2/en.php#deprecations_and_bc_breaks
- https://www.php.net/releases/8.1/en.php#deprecations_and_bc_breaks

> …add official support for PHP 8.3 now that it has been released.

Create a pull request to allow version 8.3 and we will be happy to review it.
Thanks in advance! 👍🏻

**Comment by GuySartorelli** [comment]
I've raised https://github.com/laminas/laminas-ldap/pull/47

Personally I don't think PHP does introduce breaking changes in minor releases, other than new deprecation warnings which aren't breaking changes for this library I wouldn't expect... but even if it does, I'd argue that you're more likely to have those problems fixed quickly if you let people install with the new version of PHP and therefore _find_ those broken things. In the meantime, they can avoid the bugs by just not upgrading their PHP version (which is effectively the current approach anyway).

That said, I'm not here to argue or to change your processes, so I've just added `~8.3.0` into the dependency constraint.

**Comment by Ocramius** [comment]
> Personally I don't think PHP does introduce breaking changes in minor releases

As a long-term OSS maintainer, this is not true :-) 

Anyway, expanding the constraint once a version can be tested is the right way to do this.

You can read more on this topic at https://github.com/laminas/laminas-diactoros/issues/117#issuecomment-1267306142, where I detailed exactly why you can't and shouldn't use `^8.0`, and never-ever `>=8.0` :-)

**Comment by GuySartorelli** [comment]
Fair enough, like I say I don't agree but I'm not here to change your processes. I don't subscribe to the idea that there is an objective right way for this constraint, but I accept that this is the way the maintainers have decided is right _for this project_.

**Comment by Ocramius** [comment]
It may not be the right way for you, but it's objectively the SemVer way.

**Comment by GuySartorelli** [comment]
I'm not here to argue with you so I won't. :) this conversation isn't pertinent to this issue in any case.

**Comment by GuySartorelli** [comment]
I'm going to close this issue now. The conversation has gone off topic and there's a PR open to implement the support this issue was intended to encourage.
