### ISSUE TITLE
CI does not use online tests and many tests are skipped

### ISSUE THREAD

**Issue by Xerkus** [laminas/laminas-ldap#48]
CI environment does not have ldap server setup for online testing and many tests end up skipped.

Looks like it was lost in migration to github actions. Those tests must be re-enabled.

**Comment by Ocramius** [comment]
IMO not part of current milestone, but certainly a problem.

**Comment by Xerkus** [comment]
@Ocramius Because majority of the tests are not run we do not know if it is compatible. In fact, I know that while support was declared for 8.1+ this package was not fully compatible in <=2.17 as evidenced by fatal errors when code sniffer tried to load some classes under php 8.1.
Until tests are running I do not know if just released version is compatbile.
