### ISSUE TITLE
PHP 7.4 : Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by MajuTo** [laminas/laminas-ldap#6]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 2.10.1

#### Summary

When using searchEntries() with php 7.4, i'm getting "Trying to access array offset on value of type bool" error.

#### Current behavior
When using searchEntries($filter,$baseDn, 1, [], 'sn' ) or search($filter,$baseDn, 1, [], 'sn' )->toArray() i'm getting this exception, only on php7.4

 ErrorException
Trying to access array offset on value of type bool
…/vendor/laminas/laminas-ldap/src/Collection/DefaultIterator.php 319 

#### Expected behavior

Should return an array of results

**Comment by Jay04653** [comment]
The issue was migrated from ZF.
I've updated my instance like this to avoid an issue: `$this->current = $nextEntry['resource'] ?? null;`

**Comment by michalbundyra** [comment]
Thanks for reporting. Fixed in 2.10.2 release.

**Comment by CongDatt** [comment]
![image](https://user-images.githubusercontent.com/62832416/83349860-1012a000-a362-11ea-833b-bdf2c9691fbd.png)
I have the same problem . plz help me

**Comment by TrillionaireElias** [comment]
public function getUsername() {
		return $this->sqlData["username"];
	}

   ................................................................................................if no-
t work change the 

return $Row['Data'] ?? 'username';

and another option you
can use as such.....

$Row['Data'] ??= 'username';
return $Row['Data'];
